FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY server.keystore server.keystore
COPY UnlimitedJCEPolicyJDK8/* /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.261.x86_64/jre/lib/security/
COPY target/MobileAppConfServer-0.0.1-SNAPSHOT.jar Config-Server.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","Config-Server.jar"]